name: CI
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build
      - run: npm run lint
  unit-test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, ubuntu-16.04, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - run: lsb_release -a
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      - run: echo "TEST_CI_OS_NAME=${{matrix.os}}" >> $GITHUB_ENV
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build
      - run: npm run nyc
      - name: Generate coverage report
        run: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
